### ISSUE TITLE
Exclude source files from binary wheels

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#383]
Discussion at https://github.com/adobe-type-tools/afdko/issues/352#issuecomment-390046078

- [x] Reorganize the directory tree (#508)
- [x] Simplify imports (e.g. `from afdko import ufoTools`) (#508)
- [x] Update imports in tests (#508)
- [x] Remove `pentium`, `vc6`, `vc71`, `vc8` folders (#509)
- [x] Change tools' names to all-lowercase (#511)
- [x] Cleanup the indentation & formatting of the C files using clang-format & Google style
  - [x] autohintexe (#515)
  - [x] detype1 (#522, #523)
  - [x] makeotfexe (#524, #529, #544, #545, #547) (except for issue #548)
  - [x]  mergefonts (#553)
  - [x]  public/lib/source (#562, #563)
  - [x] public/lib/api (#566)
  - [x] public/lib/resource (#567)
  - [x]  rotatefont (#559)
  - [x]  sfntdiff (#573)
  - [x]  sfntedit (#580)
  - [x]  spot (#568)
  - [x]  tx (#560)
  - [x]  type1 (#539)

**Comment by miguelsousa** [comment]
We're going to cleanup the indentation of the C-code source files at the same time.

**Comment by miguelsousa** [comment]
@cjchapman I've added a task list to this issue

**Comment by miguelsousa** [comment]
@everyone on Monday morning (Pacific time zone) we're reshuffling the whole afdko directory tree. If you're planning to submit a PR please do it today.

**Comment by cjchapman** [comment]
Some of this was done by PR https://github.com/adobe-type-tools/afdko/pull/508

**Comment by miguelsousa** [comment]
@cjchapman `git clean -fdx` has been working well for me, in the absence of `python setup.py clean`

**Comment by miguelsousa** [comment]
Moved `setup.py` checklist items to #582

**Comment by miguelsousa** [comment]
All done.
